name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6.15, 3.7.16, 3.8.16, 3.9.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Nox
      run: |
        python -m pip install --upgrade pip setuptools
        pip install nox
    - name: Run Nox
      run: |
        nox --session=py-${{ matrix.python-version }}
